### PR TITLE
add more classes

### PR DESCRIPTION
**Pull request by SLiX69**
force_download isn't implemented yet, and documentary is missing

### CODE REVIEW

**Comment by mmarquezs** [comment]
Thanks for your work! I try to check it as soon as I can and merge it.

**Comment by mmarquezs** [comment]
I haven't test it yet but it seems fine overall. The only issue I can see is that some of the functions are called "help". I don't think it causes issues in this case but it would be better to use "_help" instead because there is a built-in function on python called "help".

**Comment by SLiX69** [comment]
Hi, good point regarding help function. I completely removed them, as you did not implement them in the other classes. 
I tested most of the functions, no problems so far!

btw thanks for your work by creating this lib!

**Comment by mmarquezs** [comment]
Merged, btw I just saw that I implemented one "help"  function and I did the same mistake as you so... there is that :P

**Pull request merged**
