### PR TITLE
Decrypt API errors in request_api

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by mmarquezs** [comment]
That's was one thing I had pending to check.  I can't check now but I think this is wrong too because some errors aren't encrypted, just without testing I'm going to guess is the login/connect/reconnect etc... errors.

**Comment by Saviq** [comment]
So maybe it should only decrypt if the JSON decoding failed?

**Comment by Saviq** [comment]
How about this?

**Comment by Saviq** [comment]
Sorry, some formatting changes got in the way, fixing...

**Comment by mmarquezs** [comment]
That's a nice way to do it. I will merge it to develop test it a little and if everything is fine I will add it to master.

**Pull request merged**
